---
- name: Setup Node
  hosts: all
  become: yes
  become_user: root
  gather_facts: yes

  roles:
    - role: network
    - role: firecracker
    - role: docker
    - role: agent
    - role: bridge
    - role: machine
