---
- name: Create firecracker bridge device file
  template:
    src: bridge.netdev
    dest: /etc/systemd/network/firecracker0.netdev
    owner: root
    group: root
    mode: 064

- name: Create firecracker bridge network file
  template:
    src: bridge.network
    dest: /etc/systemd/network/firecracker0.network
    owner: root
    group: root
    mode: 0644

- name: Restart systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes
    state: restarted

- name: Setup IP forwarding
  shell: sysctl -w net.ipv4.ip_forward=1

- name: Delete iptables rules
  shell: |
    iptables --table nat --delete POSTROUTING --out-interface eth0 -j MASQUERADE
    iptables --delete FORWARD --in-interface firecracker0 -j ACCEPT
  ignore_errors: true

- name: Setup NAT on firecracker bridge
  shell: |
    iptables --table nat --append POSTROUTING --out-interface eth0 -j MASQUERADE
    iptables --insert FORWARD --in-interface firecracker0 -j ACCEPT
    iptables -P FORWARD ACCEPT
