network:
  version: 2
  vlans:
    private:
      id: "{{ node.private_vlan_id }}"
      link: eth0 # This is a placeholder, it should be replaced by the actual interface name
      addresses:
        - "{{ node.private_ip_address }}/24"
