network:
  version: 2
  vlans:
    "{{ node.private_interface }}":
      id: "{{ node.private_vlan_id }}"
      link: "{{ node.private_vlan_link }}"
      addresses:
        - "{{ node.private_ip_address }}/24"
      routes:
        - to: "{{ node.multicast_cidr_block }}"
          scope: link
