[Interface]
PrivateKey = {{ wireguard_private_key.content | b64decode  | trim }}
Address = {{ node.wireguard_ip_address }}/24
ListenPort = 51820

[Peer] # Controller
PublicKey = {{ pilot.wireguard_public_key }}
AllowedIPs = {{ pilot.wireguard_ip_address }}/32
# Pilot doesn't have a fixed public IP, so we don't set an Endpoint here

{% for peer in peers %}
[Peer] # {{ peer.name }}
PublicKey = {{ peer.wireguard_public_key }}
AllowedIPs = {{ peer.wireguard_ip_address }}/32
# Assume all peers are reachable via their private IPs
# So, use private IP for the endpoint
Endpoint = {{ peer.private_ip_address }}:51820
{% endfor %}
