[Interface]
PrivateKey = {{ wireguard_private_key.content | b64decode  | trim }}
Address = {{ node.wireguard_ip_address }}/24
ListenPort = 51820

[Peer]
# Only peer with controller for now
PublicKey = {{ pilot.wireguard_public_key }}
AllowedIPs = {{ pilot.wireguard_ip_address }}/32
