---
- name: Copy Agent repository
  ansible.posix.synchronize:
    src: ../../../../../../agent/
    dest: /agent/
    rsync_opts:
      - --exclude=env
      - --exclude=*.pyc
      - --exclude=*.pyo
      - --exclude=__pycache__

- name: Build Agent docker image
  command: "docker build -t agent /agent"

- name: Remove old Agent container
  command: "docker rm --force agent"
  ignore_errors: true

- name: Run Agent container
  command: "docker run --detach --publish 127.0.0.1:8000:8000 --restart always --name agent agent"

