[project]
name = "agent"
version = "0.0.1"
authors = [
    { name = "Frappe", email = "aditya@frappe.io"}
]
description = "Agent"
readme = "README.md"
requires-python = ">=3.13"
license = "AGPL-3.0-only"

dependencies = [
    "Quart==0.20.0",
    "requests==2.32.3",
    "requests-unixsocket==0.4.1",
]

[build-system]
requires = ["flit_core >= 3.12.0, <4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "B017", # assertRaises(Exception) - should be more specific
    "B018", # useless expression, not assigned to anything
    "B023", # function doesn't bind loop variable - will have last iteration's value
    "B904", # raise inside except without from
    "E101", # indentation contains mixed spaces and tabs
    "E402", # module level import not at top of file
    "E501", # line too long
    "E741", # ambiguous variable name
    "F401", # "unused" imports
    "F403", # can't detect undefined names from * import
    "F405", # can't detect undefined names from * import
    "F722", # syntax error in forward type annotation
    "W191", # indentation contains tabs
    "UP030", # Use implicit references for positional format fields (translations)
    "UP031", # Use format specifiers instead of percent format
    "UP032", # Use f-string instead of `format` call (translations)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true

